### ISSUE TITLE
Missing data for ccs2 EU

### ISSUE THREAD

**Issue by jwillemsen** [Hyundai-Kia-Connect/hyundai_kia_connect_api#488]
* Hyundai / Kia Connect version: 2.19.0
* Python version:
* Operating System:

### Description

After upgrading to 2.19.0 using a kona 2024 EV which uses the new ccs2 support the following fields are missing
- heating/cooling all 4 seats
- smart key battery warning
- defrost
- back window heater

Also AC/DC Charging Limit looks strange, in the bluelink app both are set to 100, but HA shows 80
![Screenshot_20240123_132912](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/assets/47353/69ce1725-b966-4fca-afcb-42f19ecd6868)

### What I Did

Upgrade to 2.19.0

**Comment by jwillemsen** [comment]
ccs2 support was added as part of https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/480

**Comment by ZuinigeRijder** [comment]
I think this info is available, but @Bubo08 did already a great job in providing most of the other information. I got a debug log of a German Kona 2024 with my[ tool debug.py](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/blob/main/debug.py)  from [hyundai_kia_connect_monitor](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor).

heating/cooling all 4 seats
````
"Cabin": {
                    "Door": {
                        "Row2": {
                            "Right": {"Lock": 0, "Open": 0},
                            "Left": {"Lock": 0, "Open": 0},
                        },
                        "Row1": {
                            "Driver": {"Open": 0, "Lock": 0},
                            "Passenger": {"Lock": 0, "Open": 0},
                        },
                    },
                    "HVAC": {
                        "Row1": {
                            "Driver": {
                                "Temperature": {"Value": "OFF", "Unit": 0},
                                "Blower": {"SpeedLevel": 0},
                            }
                        },
                        "Vent": {
                            "AirCleaning": {"Indicator": 1, "SymbolColor": 0},
                            "FineDust": {"Level": 0},
                        },
                        "Temperature": {"RangeType": 1},
                    },
                    "RestMode": {"State": 0},
                    "Seat": {
                        "Row2": {
                            "Left": {"Climate": {"State": 2}},
                            "Right": {"Climate": {"State": 2}},
                        },
                        "Row1": {
                            "Passenger": {"Climate": {"State": 2}},
                            "Driver": {"Climate": {"State": 2}},
                        },
                    },
                    "Window": {
                        "Row1": {
                            "Driver": {"Open": 0, "OpenLevel": 0},
                            "Passenger": {"Open": 0, "OpenLevel": 0},
                        },
                        "Row2": {
                            "Left": {"Open": 0, "OpenLevel": 0},
                            "Right": {"Open": 0, "OpenLevel": 0},
                        },
                    },
                    "SteeringWheel": {
                        "Heat": {"RemoteControl": {"Step": 0}, "State": 0}
                    },
                },
````

smart key battery warning:
````
"Vehicle": {
                "Version": "CCU2024012308473901",
                "RemoteControl": {"SleepMode": 0},
                "Electronics": {
                    "Battery": {
                        "Level": 89,
                        "PowerStateAlert": {"ClassC": 2},
                        "Auxiliary": {"FailWarning": 0},
                        "Charging": {"WarningLevel": 65},
                        "SensorReliability": 0,
                    },
                    "PowerSupply": {"Ignition1": 0, "Ignition3": 0, "Accessory": 0},
                    "AutoCut": {
                        "PowerMode": 2,
                        "BatteryPreWarning": 0,
                        "DeliveryMode": 2,
                    },
                    "FOB": {"LowBattery": 0},
                },
````
defrost/back window heater:
````
"Body": {
                    "Lights": {
                        "Front": {
                            "Right": {
                                "TurnSignal": {"LampState": 0, "Warning": 0},
                                "Low": {"Warning": 0},
                                "High": {"Warning": 0},
                            },
                            "Left": {
                                "TurnSignal": {"LampState": 0, "Warning": 0},
                                "Low": {"Warning": 0},
                                "High": {"Warning": 0},
                            },
                            "HeadLamp": {"SystemWarning": 0},
                        },
                        "DischargeAlert": {"State": 0},
                        "Rear": {
                            "Left": {
                                "StopLamp": {"Warning": 0},
                                "TurnSignal": {"Warning": 0},
                            },
                            "Right": {
                                "StopLamp": {"Warning": 0},
                                "TurnSignal": {"Warning": 0},
                            },
                        },
                        "TailLamp": {"Alert": 0},
                        "Hazard": {"Alert": 0},
                    },
                    "Windshield": {
                        "Rear": {"Defog": {"State": 0}},
                        "Front": {
                            "Heat": {"State": 0},
                            "Defog": {"State": 0},
                            "WasherFluid": {"LevelLow": 0},
                        },
                    },
                    "Hood": {"Open": 0},
                    "Trunk": {"Open": 0},
                },
````

So someone could add this information, including the other information not yet filled.

**Comment by fuatakgun** [comment]
there is data sensor and its attributes hold data about vehicle

**Comment by fuatakgun** [comment]
![image](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/assets/11085566/1d1ba55b-9adb-417c-92ec-903087c86251)

**Comment by jwillemsen** [comment]
Ok, I see now that it holds all fields that there are, also the not exported ones, thanks!

**Comment by Bubo08** [comment]
Some attributes are very hard to find out but I think 
"FOB": {"LowBattery": 0}, is the low smart key battery warning.
I will integrate it.

**Comment by Bubo08** [comment]
I did also add the seat heating status.

**Comment by ZuinigeRijder** [comment]
@Bubo08 


defrost/back window heater, 0 means probably off.
````
"Windshield": {
                        "Rear": {"Defog": {"State": 0}},
                        "Front": {
                            "Heat": {"State": 0},
                            "Defog": {"State": 0},
                            "WasherFluid": {"LevelLow": 0},
                        },
````

**Comment by Bubo08** [comment]
Defrost had a bug in it. I fixed it

**Comment by Bubo08** [comment]
AC DC charging limits is also fixed. It would be interesting if somebody can test it with home assistant as my EV9 is in the car repair shop.

**Comment by cdnninja** [comment]
@jwillemsen  could you update from "master" in HACS using the redownload button and let us know if any issues?

**Comment by jwillemsen** [comment]
Only back window heater is still missing, all others are there now, thanks for all work

**Comment by Bubo08** [comment]
Is setting the AC and DC limits working? You are able to change the values by home assistant?

**Comment by jwillemsen** [comment]
Setting them doesn’t work yet

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 4:58:46 PM (2 occurrences)
Last logged: 4:59:07 PM

[2601329896] Duplicate request - Duplicate request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2173, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2210, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 111, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/kia_uvo/number.py", line 94, in async_set_native_value
    await self.coordinator.async_force_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 159, in async_force_update_all
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 114, in force_refresh_all_vehicles_states
    self.force_refresh_vehicle_state(vehicle_id)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 119, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 369, in force_refresh_vehicle_state
    state = self._get_forced_vehicle_state(token, vehicle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1049, in _get_forced_vehicle_state
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 119, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DuplicateRequestError: Duplicate request - Duplicate request

**Comment by jwillemsen** [comment]
Bluelink also shows V2L limit and AC large power, these are not yet in HA

**Comment by jwillemsen** [comment]
Ok, errors happens when you change the same value a few seconds after each time. But, changing one value to 90 doesn't change the value in the bluelink app

**Comment by jwillemsen** [comment]
V2L discharge limitation is here in data

![Schermafbeelding 2024-01-31 om 19 15 16](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/assets/47353/480bb2c3-b1b6-4361-bec4-0c1f13098aa0)

**Comment by Bubo08** [comment]
If I run the following test program:
```
    vm.check_and_refresh_token()
    vm.update_all_vehicles_with_cached_state()
    for vehicle_id in vm.vehicles.keys():
      ac = 100
      dc = 100
      vm.set_charge_limits(vehicle_id, ac, dc)

```
Then the values are changed in my KIA connect app. So it should work. Can you please retest and provide the debug log?

**Comment by jwillemsen** [comment]
Thanks for the code, just tried that, and that works. Maybe something is broken at a higher layer, I will retest when there is a release with your fixes

**Comment by jwillemsen** [comment]
Attaching the output of https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/blob/main/debug.py for my Kona 2024, all data provided by Hyundai for reference (cleared some confidential fields)

[kona2024data.txt](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/files/14123615/kona2024data.txt)

**Comment by Bubo08** [comment]
I think we should close the bug and open a new one in kia_uvo.

**Comment by jwillemsen** [comment]
Closing, we have separate issues for the last remaining sensors
