### ISSUE TITLE
Wiki: Add Hyundai Europe Login Flow Guide alongside Kia guide

### ISSUE THREAD

**Issue by chrisf4lc0n** [Hyundai-Kia-Connect/hyundai_kia_connect_api#923]
## Description
The wiki currently has the Kia Europe Login Flow guide, but Hyundai users need their own guide due to slightly different endpoints and client credentials.

## Request
Please add a new wiki page "Hyundai-Europe-Login-Flow" to complement the existing Kia guide.

## Proposed Content
I've prepared a complete guide following the same format as the Kia guide, I have also slightly modified the original script as the original script hung on "Please log in manually in the browser window. The script will wait for you to complete the login...:"

### Hyundai Europe Login Flow

# Hyundai Europe Login Flow

Hyundai has recently made changes to its login flow, implementing Google reCAPTCHA during login. It is not currently possible to solve this automatically with Python, which is why manual steps are necessary to obtain a refresh token.

Python scripts have been developed for this purpose, which automate most of the process of obtaining the necessary `refresh_token`, which must then be used as a password in Home Assistant and other integrations.

> **⚠️ SECURITY WARNING**  
> **NEVER EVER publish your refresh token or access token.** If someone gets them, they will have full access to your Hyundai account and thus also to your car! No email address or password is required!

If you have any questions or need assistance, please review and utilize the [[discussion forum](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/discussions)](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/discussions).

See [[issue #1343](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1343)](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1343) if you are interested in more background information.

## Download the Script

The unified script for all methods is available here:
**[[HyundaiFetchApiTokensSelenium.py](https://gist.github.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe)](https://gist.github.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe)**

## Prerequisites

> **Important:** You must use Chrome or one of its forks (Chromium, Brave, etc.). Chrome browser must be installed on your system.

### Windows (PowerShell)

```powershell
# Preparations
mkdir HyundaiToken
cd HyundaiToken
py -m venv .venv
.\.venv\Scripts\Activate.ps1
python.exe -m pip install --upgrade pip
pip install selenium requests webdriver-manager

# Download script
iwr -UseBasicParsing -OutFile HyundaiFetchApiTokensSelenium.py https://gist.githubusercontent.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe/raw/

# Start script
py .\HyundaiFetchApiTokensSelenium.py

# Copy Refresh token from output and use it as the password in the HA integration setup!
```

### Linux (Ubuntu/Debian)

```bash
# Install dependencies
sudo apt update
sudo apt install chromium-browser chromium-chromedriver python3-pip python3-venv

# Setup and run
mkdir ~/HyundaiToken && cd ~/HyundaiToken
python3 -m venv .venv
source .venv/bin/activate
pip install selenium requests webdriver-manager

# Download and run script
wget -O HyundaiFetchApiTokensSelenium.py https://gist.githubusercontent.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe/raw/
python3 HyundaiFetchApiTokensSelenium.py
```

### Linux (Arch/Manjaro/CachyOS)

```bash
# Install dependencies
sudo pacman -S chromium
yay -S chromedriver  # or: paru -S chromedriver

# Setup and run
mkdir ~/HyundaiToken && cd ~/HyundaiToken
python -m venv .venv
source .venv/bin/activate  # For bash/zsh
# or
source .venv/bin/activate.fish  # For fish shell
pip install selenium requests webdriver-manager

# Download and run script
wget -O HyundaiFetchApiTokensSelenium.py https://gist.githubusercontent.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe/raw/
python HyundaiFetchApiTokensSelenium.py
```

### macOS

```bash
# Install Homebrew if needed
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install Chrome and Python
brew install --cask google-chrome
brew install python

# Setup and run
mkdir ~/HyundaiToken && cd ~/HyundaiToken
python3 -m venv .venv
source .venv/bin/activate
pip install selenium requests webdriver-manager

# Download and run script
curl -o HyundaiFetchApiTokensSelenium.py https://gist.githubusercontent.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe/raw/
python3 HyundaiFetchApiTokensSelenium.py
```

## How It Works

When you run the script:

1. **A Chrome browser window will open automatically**
2. **The script navigates to Hyundai's login page**
3. **You manually log in and solve the reCAPTCHA**
4. **The script automatically:**
   - Detects successful login
   - Retrieves the authorization code
   - Exchanges it for tokens
   - Displays your refresh token

### Example Output:
```
Opening login page...
==================================================
Please log in manually in the browser window.
The script will wait for you to complete the login...
==================================================

✅ Login successful! Element found.
✅ Your tokens are:

- Refresh Token: M2M2OG................................YOTG5
- Access Token: eyJhbGc.........................0_AijpHXp0yg

Cleaning up and closing the browser.
```

## Script Files

The complete Selenium script is available as a GitHub Gist:
- **[[HyundaiFetchApiTokensSelenium.py](https://gist.github.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe)](https://gist.github.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe)**

### Technical Details
- **CLIENT_ID:** `6d477c38-3ca4-4cf3-9557-2a1929a94654`  
- **CLIENT_SECRET:** `KUy49XxPzLpLuoK0xhBC77W6VXhmtQR9iQhmIFjjoY4IpxsV`
- **User Agent:** `Mozilla/5.0 (Linux; Android 4.1.1; Galaxy Nexus Build/JRO03C) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166 Mobile Safari/535.19_CCS_APP_AOS`

## Using the Refresh Token

Once you have obtained your refresh token:

1. **In Home Assistant:**
   - Go to Settings → Devices & Services → Add Integration
   - Search for "Hyundai / Kia Connect"
   - Select your region (Europe)
   - Enter your email address as username
   - **Enter the refresh token as your password** (NOT your actual Hyundai password)
   - Select Hyundai as the brand

2. **Token Validity:**
   - The refresh token typically remains valid for an extended period
   - If authentication fails, generate a new refresh token using this guide

### Common Issues

1. **"Invalid client secret" error**
   - Ensure you're using the correct CLIENT_ID and CLIENT_SECRET in the script
   - The authorization code expires quickly (60 seconds), so exchange it immediately

2. **ChromeDriver version mismatch**
   - Install webdriver-manager: `pip install webdriver-manager`
   - Or manually download matching ChromeDriver from [[ChromeDriver Downloads](https://chromedriver.chromium.org/)](https://chromedriver.chromium.org/)

3. **"Code not exist in redis" error**
   - The authorization code has expired
   - Get a new code and exchange it within 60 seconds

4. **Browser not found**
   - Ensure Chrome/Chromium is installed
   - Check the binary path in the script matches your installation

### Getting Help

- Check the [[discussions](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/discussions)](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/discussions)
- Review [[issue #1343](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1343)](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1343) for background
- Ensure you're using the exact User Agent specified

## Contributing

This guide was created by the Hyundai-Kia-Connect community:
- Original Kia script by [[@marvinwankersteen](https://github.com/marvinwankersteen)](https://github.com/marvinwankersteen)  
- Selenium version by [[@fuatakgun](https://github.com/fuatakgun)](https://github.com/fuatakgun)
- Windows instructions by [[@anttitane](https://github.com/anttitane)](https://github.com/anttitane)
- CLIENT_SECRET discovered through mitmproxy analysis

If you find improvements or issues with this process:
1. Fork the repository
2. Create a feature branch
3. Submit a pull request with your changes
4. Or open an issue describing the problem

## Disclaimer

This is an unofficial tool. Use at your own risk. The authors are not responsible for any damage or loss caused by the use of this tool. Always keep your tokens secure and never share them publicly.

I only tested Debian (Ubuntu) and Arch (CachyOS) guides and they are definitely working. Windows and Mac guides have been collated from the users posts.

Important: You must use Chrome or one of its forks (Chromium, Brave, etc.). Chrome browser must be installed on your system.

## Resources
- Working Selenium script: https://gist.github.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe
- Tested on Windows, Linux (Ubuntu/Arch), and macOS
- Uses CLIENT_ID: 6d477c38-3ca4-4cf3-9557-2a1929a94654
- Addresses issues in #1343

## Why Separate Guide?
While the process is similar to Kia, Hyundai uses:
- Different login URL parameters
- Different CLIENT_ID and CLIENT_SECRET
- Different initial redirect endpoints

Having both guides will help users find the correct instructions for their brand immediately.

Thanks to @marvinwankersteen, @fuatakgun, and @anttitane for the foundation work!

**Comment by ikerasLT** [comment]
I have followed your guide on macOS but the script fails not being able to open chrome although it's there.

Output:
```
(.venv) ➜  HyundaiToken python3 HyundaiFetchApiTokensSelenium.py

Chrome/Chromium not found! Install with: sudo apt install chromium-browser
```

EDIT:
works with this script:
https://gist.githubusercontent.com/Maaxion/22a38ba8fb06937da18482ddf35171ac/raw/442c0b5167d5b092123088055e5a407c034ed720/gistfile1.txt

**Comment by thkrmr** [comment]
Amending binary path finding to this
```
# Find Chrome/Chromium
def find_chrome():
    paths = ['/usr/bin/chromium-browser', '/usr/bin/google-chrome', 
             '/usr/bin/google-chrome-stable', '/snap/bin/chromium', '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome']
    for path in paths:
        if os.path.exists(path):
            return path
    return None
```
will make it compatible with macOS. I just successfully went through the auth flow with Chrome on macOS having done this.

**Comment by Maaxion** [comment]
Selenium also works on macos. 

IMO if this is added to the wiki, it would be better to get away from scripts hosted on random peoples gists, and have it in the repo itself.

Gists can easily later on be edited with malicious content.

**Comment by thkrmr** [comment]
@Maaxion Selenium wasn't the issue, the issue was in the gist linked above, it has steps for macOS but the binary path finding in the script had no macOS compatible path listed where Chrome is usually found. 
Certainly +1 on not relying on gists going forward, but then again even today the Kia login flow page links to a gists by @marvinwankersteen and @fuatakgun

**Comment by TheHuskyCrobats** [comment]
`(.venv) PS C:\Users\crist\HyundaiToken> py .\HyundaiFetchApiTokensSelenium.py
Chrome/Chromium not found! Install with: sudo apt install chromium-browser
(.venv) PS C:\Users\crist\HyundaiToken>`

I have the above error in Windows, even the chrome is installed,

**Comment by TheHuskyCrobats** [comment]
I forget to ask, after retrieving the token (if I can do it), i need to add another hub in integration? to delete the old one? I cannot find the reconfigure option where I should insert the token.

**Comment by thkrmr** [comment]
@TheHuskyCrobats the auth should've failed and HA notices this and offers you to reauth, you're then presented with the login form this is where you enter the token instead of the password.

**Comment by sercanincesu** [comment]
> I have followed your guide on macOS but the script fails not being able to open chrome although it's there.
> 
> Output:
> 
> ```
> (.venv) ➜  HyundaiToken python3 HyundaiFetchApiTokensSelenium.py
> 
> Chrome/Chromium not found! Install with: sudo apt install chromium-browser
> ```
> 
> EDIT: works with this script: https://gist.githubusercontent.com/Maaxion/22a38ba8fb06937da18482ddf35171ac/raw/442c0b5167d5b092123088055e5a407c034ed720/gistfile1.txt

I had "Chrome/Chromium not found!" error as well, when I copy/paste the code for my hyundai. I fixed with this steps: 
-Open windows powershell 
-Write : pip install chromedriver-autoinstaller
-Write: pip install selenium requests webdriver-manager chromedriver-autoinstaller
-Write: notepad .\HyundaiFetchApiTokensSelenium.py
-With last code, a notepad document (named HyundaiFetchApiTokensSelenium.py) will open. You can replace that all code in notepad document with this one and save it:

```
# hyundai_token_windows.py (Windows uyumlu versiyon)
import re
import os
import time
import requests
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
import chromedriver_autoinstaller

# Otomatik olarak uygun ChromeDriver'ı indir ve yükle
chromedriver_autoinstaller.install()

# Windows'ta olası Chrome yolları
possible_chrome_paths = [
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    os.path.expandvars(r"%LocalAppData%\Google\Chrome\Application\chrome.exe"),
]

# Chrome'un yolunu bul
chrome_path = None
for path in possible_chrome_paths:
    if os.path.exists(path):
        chrome_path = path
        break

if not chrome_path:
    print("⚠️ Chrome not found on this system. Please install Google Chrome first:")
    print("https://www.google.com/chrome/")
    exit(1)

CLIENT_ID = "6d477c38-3ca4-4cf3-9557-2a1929a94654"
CLIENT_SECRET = "KUy49XxPzLpLuoK0xhBC77W6VXhmtQR9iQhmIFjjoY4IpxsV"
BASE_URL = "https://idpconnect-eu.hyundai.com/auth/api/v2/user/oauth2/"

# Chrome ayarları
options = Options()
options.binary_location = chrome_path
options.add_argument("--window-size=800,600")
options.add_argument("--window-position=0,0")
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument(
    "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/125.0.0.0 Safari/537.36_CCS_APP_AOS"
)

# WebDriver başlat
driver = webdriver.Chrome(service=Service(), options=options)

# Login sayfasını aç
driver.get(
    f"{BASE_URL}authorize?client_id=peuhyundaiidm-ctb&redirect_uri=https%3A%2F%2Fctbapi.hyundai-europe.com%2Fapi%2Fauth&nonce=&state=PL_&scope=openid+profile+email+phone&response_type=code&connector_client_id=peuhyundaiidm-ctb&connector_scope=&connector_session_key=&country=&captcha=1&ui_locales=en-US"
)

print("\n" + "=" * 60)
print("🔑 LOGIN REQUIRED: Complete login and reCAPTCHA in the opened browser")
print("=" * 60)
input("\nPress Enter AFTER successful login...")

# Auth code al
driver.get(
    f"{BASE_URL}authorize?response_type=code&client_id={CLIENT_ID}&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token&lang=de&state=ccsp"
)
time.sleep(2)

match = re.search(r"code=([^&]+)", driver.current_url)
if match:
    code = match.group(1)
    response = requests.post(
        f"{BASE_URL}token",
        data={
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": "https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token",
            "client_id": CLIENT_ID,
            "client_secret": CLIENT_SECRET,
        },
    )

    if response.status_code == 200:
        token = response.json().get("refresh_token")
        print(f"\n{'='*60}\n✅ REFRESH TOKEN:\n{token}\n{'='*60}")
        print("Use this as PASSWORD in Home Assistant integration setup!")
    else:
        print(f"❌ Error: {response.text}")
else:
    print("⚠️ No authorization code found in URL")

driver.quit()
 
```

-Then a chrome page will open to login your hyundai account. 
-After you login, you turn back to windows powershell and press enter button. Your token code will appear on your windows powershell.
-You can use that code in windows powershell as your **password** to login on your home assistant integration.

**Comment by TheHuskyCrobats** [comment]
> [@TheHuskyCrobats](https://github.com/TheHuskyCrobats) the auth should've failed and HA notices this and offers you to reauth, you're then presented with the login form this is where you enter the token instead of the password.

well ... it is failing but not offering anything but to configure.

<img width="721" height="320" alt="Image" src="https://github.com/user-attachments/assets/19ffefaf-9d12-4aee-9633-cedaba856403" />

**Comment by kitos9112** [comment]
Yup, enabling debug logging on my HASS implementation gets me here.

I'm running the latest version so far.


```
2025-10-16 13:42:49.497 ERROR (MainThread) [custom_components.kia_uvo.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 148, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 92, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        api.login, user_input[CONF_USERNAME], user_input[CONF_PASSWORD]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 185, in login
    _, access_token, authorization_code, expires_in = self._get_access_token(
                                                      ~~~~~~~~~~~~~~~~~~~~~~^
        stamp, refresh_token
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1354, in _get_access_token
    _check_response_for_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/ApiImplType1.py", line 111, in _check_response_for_errors
    raise AuthenticationError(retMSG)
hyundai_kia_connect_api.exceptions.AuthenticationError: Received unexpected statusCode`
```

> > [@TheHuskyCrobats](https://github.com/TheHuskyCrobats) the auth should've failed and HA notices this and offers you to reauth, you're then presented with the login form this is where you enter the token instead of the password.
> 
> well ... it is failing but not offering anything but to configure.
> <img alt="Image" width="721" height="320" src="https://private-user-images.githubusercontent.com/149390002/502015201-19ffefaf-9d12-4aee-9633-cedaba856403.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjA2MTg5MzUsIm5iZiI6MTc2MDYxODYzNSwicGF0aCI6Ii8xNDkzOTAwMDIvNTAyMDE1MjAxLTE5ZmZlZmFmLTlkMTItNGFlZS05NjMzLWNlZGFiYTg1NjQwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTAxNlQxMjQzNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYjMxNDVkODBjODAzYWE0ZDg0ODhiMzJkZDY0MzFkOGQxYmVjZDU2YzA2YjJhYjQ5NTAyZDkwMjQyYWFjOTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6ELZMn1ZMWIBclhmw5uFsIH08CaWJkBnN3-NxtStXHI">

**Comment by TheHuskyCrobats** [comment]
No ideea what to do ...

**Comment by nickjcowley** [comment]
Ive followed instructions, and received a refresh token, but still not being accepted by HA integration.  Cant work out why.... saying 'unexpected error' on inputting credentials.  Restarted HA, rolled back to prev Bluelink integration version... cant think of what else to do....

**Comment by haegele100** [comment]
Hello, Chrome keeps closing for me. The window opens a second time and closes again. What am I doing wrong?

**Comment by Isoldael** [comment]
> > I have followed your guide on macOS but the script fails not being able to open chrome although it's there.
> > Output:
> > ```
> > (.venv) ➜  HyundaiToken python3 HyundaiFetchApiTokensSelenium.py
> > 
> > Chrome/Chromium not found! Install with: sudo apt install chromium-browser
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > EDIT: works with this script: https://gist.githubusercontent.com/Maaxion/22a38ba8fb06937da18482ddf35171ac/raw/442c0b5167d5b092123088055e5a407c034ed720/gistfile1.txt
> 
> I had "Chrome/Chromium not found!" error as well, when I copy/paste the code for my hyundai. I fixed with this steps: -Open windows powershell -Write : pip install chromedriver-autoinstaller -Write: pip install selenium requests webdriver-manager chromedriver-autoinstaller -Write: notepad .\HyundaiFetchApiTokensSelenium.py -With last code, a notepad document (named HyundaiFetchApiTokensSelenium.py) will open. You can replace that all code in notepad document with this one and save it:
> 
> ```
> # hyundai_token_windows.py (Windows uyumlu versiyon)
> import re
> import os
> import time
> import requests
> from selenium import webdriver
> from selenium.webdriver.chrome.service import Service
> from selenium.webdriver.chrome.options import Options
> import chromedriver_autoinstaller
> 
> # Otomatik olarak uygun ChromeDriver'ı indir ve yükle
> chromedriver_autoinstaller.install()
> 
> # Windows'ta olası Chrome yolları
> possible_chrome_paths = [
>     r"C:\Program Files\Google\Chrome\Application\chrome.exe",
>     r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
>     os.path.expandvars(r"%LocalAppData%\Google\Chrome\Application\chrome.exe"),
> ]
> 
> # Chrome'un yolunu bul
> chrome_path = None
> for path in possible_chrome_paths:
>     if os.path.exists(path):
>         chrome_path = path
>         break
> 
> if not chrome_path:
>     print("⚠️ Chrome not found on this system. Please install Google Chrome first:")
>     print("https://www.google.com/chrome/")
>     exit(1)
> 
> CLIENT_ID = "6d477c38-3ca4-4cf3-9557-2a1929a94654"
> CLIENT_SECRET = "KUy49XxPzLpLuoK0xhBC77W6VXhmtQR9iQhmIFjjoY4IpxsV"
> BASE_URL = "https://idpconnect-eu.hyundai.com/auth/api/v2/user/oauth2/"
> 
> # Chrome ayarları
> options = Options()
> options.binary_location = chrome_path
> options.add_argument("--window-size=800,600")
> options.add_argument("--window-position=0,0")
> options.add_argument("--disable-blink-features=AutomationControlled")
> options.add_argument(
>     "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
>     "AppleWebKit/537.36 (KHTML, like Gecko) "
>     "Chrome/125.0.0.0 Safari/537.36_CCS_APP_AOS"
> )
> 
> # WebDriver başlat
> driver = webdriver.Chrome(service=Service(), options=options)
> 
> # Login sayfasını aç
> driver.get(
>     f"{BASE_URL}authorize?client_id=peuhyundaiidm-ctb&redirect_uri=https%3A%2F%2Fctbapi.hyundai-europe.com%2Fapi%2Fauth&nonce=&state=PL_&scope=openid+profile+email+phone&response_type=code&connector_client_id=peuhyundaiidm-ctb&connector_scope=&connector_session_key=&country=&captcha=1&ui_locales=en-US"
> )
> 
> print("\n" + "=" * 60)
> print("🔑 LOGIN REQUIRED: Complete login and reCAPTCHA in the opened browser")
> print("=" * 60)
> input("\nPress Enter AFTER successful login...")
> 
> # Auth code al
> driver.get(
>     f"{BASE_URL}authorize?response_type=code&client_id={CLIENT_ID}&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token&lang=de&state=ccsp"
> )
> time.sleep(2)
> 
> match = re.search(r"code=([^&]+)", driver.current_url)
> if match:
>     code = match.group(1)
>     response = requests.post(
>         f"{BASE_URL}token",
>         data={
>             "grant_type": "authorization_code",
>             "code": code,
>             "redirect_uri": "https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token",
>             "client_id": CLIENT_ID,
>             "client_secret": CLIENT_SECRET,
>         },
>     )
> 
>     if response.status_code == 200:
>         token = response.json().get("refresh_token")
>         print(f"\n{'='*60}\n✅ REFRESH TOKEN:\n{token}\n{'='*60}")
>         print("Use this as PASSWORD in Home Assistant integration setup!")
>     else:
>         print(f"❌ Error: {response.text}")
> else:
>     print("⚠️ No authorization code found in URL")
> 
> driver.quit()
>  
> ```
> 
> -Then a chrome page will open to login your hyundai account. -After you login, you turn back to windows powershell and press enter button. Your token code will appear on your windows powershell. -You can use that code in windows powershell as your **password** to login on your home assistant integration.

This script exits immediately after running, so it's hard to catch your refresh token. I would recommend adding the following line to the end to make sure Powershell stays open and you get the time to copy your token:

```
# Add this line at the end
input("\nPress Enter to exit...")
```

**Comment by robotfishe** [comment]
For anyone trying to get this working on NixOS, here's how I managed it - could be worth adding to the Wiki page.

First, start an ephemeral shell with the python packages you need and grab the script file:

```
nix-shell -p python313 chromium chromedriver python313Packages.selenium python313Packages.requests python313Packages.webdriver-manager
wget -O HyundaiFetchApiTokensSelenium.py https://gist.githubusercontent.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe/raw/040a7bb27d0266c52b97b6f360a00bfcb7a476f5/gistfile1.txt
```

IMPORTANT: open the HyundayFetchApiTokensSelenium.py file and change the line:
`    driver = webdriver.Chrome(service=Service('/usr/bin/chromedriver'), options=options)`
to
`    driver = webdriver.Chrome(options=options)`

This makes the script find chromedriver in your PATH rather than looking in /usr/bin, which is not where anything lives in NixOS.

Now run the script:
`python3 HyundaiFetchApiTokensSelenium.py`

**Comment by sercanincesu** [comment]
I have waaaay more simple solution for you Hyundai user guys.  I created two file you can download here: https://drive.google.com/file/d/1LDcd6ouR72xl9H9IN7p4jGOWmw3TYk-R/view?usp=sharing

The only thing you should do;
-Download and extract as folder (2 files in folder must have in same folder!),
-Double click launch_hyundai_token.bat
-Hyundai login page will open by chrome. login with your account
-Turn back to cmd/powershell screen and click enter
-Bam! You will have new refresh token. You can now go to home assistant integration and use that token as your password. 




> > I have followed your guide on macOS but the script fails not being able to open chrome although it's there.
> > Output:
> > ```
> > (.venv) ➜  HyundaiToken python3 HyundaiFetchApiTokensSelenium.py
> > 
> > Chrome/Chromium not found! Install with: sudo apt install chromium-browser
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > EDIT: works with this script: https://gist.githubusercontent.com/Maaxion/22a38ba8fb06937da18482ddf35171ac/raw/442c0b5167d5b092123088055e5a407c034ed720/gistfile1.txt
> 
> I had "Chrome/Chromium not found!" error as well, when I copy/paste the code for my hyundai. I fixed with this steps: -Open windows powershell -Write : pip install chromedriver-autoinstaller -Write: pip install selenium requests webdriver-manager chromedriver-autoinstaller -Write: notepad .\HyundaiFetchApiTokensSelenium.py -With last code, a notepad document (named HyundaiFetchApiTokensSelenium.py) will open. You can replace that all code in notepad document with this one and save it:
> 
> ```
> # hyundai_token_windows.py (Windows uyumlu versiyon)
> import re
> import os
> import time
> import requests
> from selenium import webdriver
> from selenium.webdriver.chrome.service import Service
> from selenium.webdriver.chrome.options import Options
> import chromedriver_autoinstaller
> 
> # Otomatik olarak uygun ChromeDriver'ı indir ve yükle
> chromedriver_autoinstaller.install()
> 
> # Windows'ta olası Chrome yolları
> possible_chrome_paths = [
>     r"C:\Program Files\Google\Chrome\Application\chrome.exe",
>     r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
>     os.path.expandvars(r"%LocalAppData%\Google\Chrome\Application\chrome.exe"),
> ]
> 
> # Chrome'un yolunu bul
> chrome_path = None
> for path in possible_chrome_paths:
>     if os.path.exists(path):
>         chrome_path = path
>         break
> 
> if not chrome_path:
>     print("⚠️ Chrome not found on this system. Please install Google Chrome first:")
>     print("https://www.google.com/chrome/")
>     exit(1)
> 
> CLIENT_ID = "6d477c38-3ca4-4cf3-9557-2a1929a94654"
> CLIENT_SECRET = "KUy49XxPzLpLuoK0xhBC77W6VXhmtQR9iQhmIFjjoY4IpxsV"
> BASE_URL = "https://idpconnect-eu.hyundai.com/auth/api/v2/user/oauth2/"
> 
> # Chrome ayarları
> options = Options()
> options.binary_location = chrome_path
> options.add_argument("--window-size=800,600")
> options.add_argument("--window-position=0,0")
> options.add_argument("--disable-blink-features=AutomationControlled")
> options.add_argument(
>     "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
>     "AppleWebKit/537.36 (KHTML, like Gecko) "
>     "Chrome/125.0.0.0 Safari/537.36_CCS_APP_AOS"
> )
> 
> # WebDriver başlat
> driver = webdriver.Chrome(service=Service(), options=options)
> 
> # Login sayfasını aç
> driver.get(
>     f"{BASE_URL}authorize?client_id=peuhyundaiidm-ctb&redirect_uri=https%3A%2F%2Fctbapi.hyundai-europe.com%2Fapi%2Fauth&nonce=&state=PL_&scope=openid+profile+email+phone&response_type=code&connector_client_id=peuhyundaiidm-ctb&connector_scope=&connector_session_key=&country=&captcha=1&ui_locales=en-US"
> )
> 
> print("\n" + "=" * 60)
> print("🔑 LOGIN REQUIRED: Complete login and reCAPTCHA in the opened browser")
> print("=" * 60)
> input("\nPress Enter AFTER successful login...")
> 
> # Auth code al
> driver.get(
>     f"{BASE_URL}authorize?response_type=code&client_id={CLIENT_ID}&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token&lang=de&state=ccsp"
> )
> time.sleep(2)
> 
> match = re.search(r"code=([^&]+)", driver.current_url)
> if match:
>     code = match.group(1)
>     response = requests.post(
>         f"{BASE_URL}token",
>         data={
>             "grant_type": "authorization_code",
>             "code": code,
>             "redirect_uri": "https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token",
>             "client_id": CLIENT_ID,
>             "client_secret": CLIENT_SECRET,
>         },
>     )
> 
>     if response.status_code == 200:
>         token = response.json().get("refresh_token")
>         print(f"\n{'='*60}\n✅ REFRESH TOKEN:\n{token}\n{'='*60}")
>         print("Use this as PASSWORD in Home Assistant integration setup!")
>     else:
>         print(f"❌ Error: {response.text}")
> else:
>     print("⚠️ No authorization code found in URL")
> 
> driver.quit()
>  
> ```
> 
> -Then a chrome page will open to login your hyundai account. -After you login, you turn back to windows powershell and press enter button. Your token code will appear on your windows powershell. -You can use that code in windows powershell as your **password** to login on your home assistant integration.

**Comment by thkrmr** [comment]
@sercanincesu proposing folks using Windows download a zip off of Google Drive in a GitHub comment is peak irony. Don't.

**Comment by sercanincesu** [comment]
> [@sercanincesu](https://github.com/sercanincesu) proposing folks using Windows download a zip off of Google Drive in a GitHub comment is peak irony. Don't.
You are right maybe.. The reason I share it as a downloadable link is to make easier for people who is not too much into coding things.

Hovewer, I'm writing here the codes:

This codes should save as name: "hyundai_token.py"
```
# hyundai_token.py
import re
import time
import requests
import platform
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import chromedriver_autoinstaller

# Detect OS
IS_WINDOWS = platform.system() == "Windows"

# Install chromedriver automatically
chromedriver_autoinstaller.install()

# Chrome options
options = Options()
options.add_argument("--window-size=1000,800")
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument(
    "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/125.0.0.0 Safari/537.36_CCS_APP_AOS"
)

# Launch Chrome
driver = webdriver.Chrome(options=options)

# Hyundai login URL
BASE_URL = "https://idpconnect-eu.hyundai.com/auth/api/v2/user/oauth2/"
LOGIN_URL = (
    f"{BASE_URL}authorize?"
    "client_id=peuhyundaiidm-ctb&"
    "redirect_uri=https%3A%2F%2Fctbapi.hyundai-europe.com%2Fapi%2Fauth&"
    "nonce=&state=PL_&"
    "scope=openid+profile+email+phone&"
    "response_type=code&"
    "connector_client_id=peuhyundaiidm-ctb&"
    "connector_scope=&connector_session_key=&country=&captcha=1&"
    "ui_locales=en-US&lang=en"
)

driver.get(LOGIN_URL)

print("\n" + "=" * 60)
print("🔑 LOGIN REQUIRED: Complete login and reCAPTCHA in the opened browser.")
print("=" * 60)
input("\nPress ENTER after login is complete...")

# After login, get the authorization code from redirected URL
driver.get(
    f"{BASE_URL}authorize?response_type=code&client_id=6d477c38-3ca4-4cf3-9557-2a1929a94654&redirect_uri=https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token&lang=en&state=ccsp"
)
time.sleep(2)

match = re.search(r"code=([^&]+)", driver.current_url)
if match:
    code = match.group(1)
    response = requests.post(
        f"{BASE_URL}token",
        data={
            "grant_type": "authorization_code",
            "code": code,
            "redirect_uri": "https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token",
            "client_id": "6d477c38-3ca4-4cf3-9557-2a1929a94654",
            "client_secret": "KUy49XxPzLpLuoK0xhBC77W6VXhmtQR9iQhmIFjjoY4IpxsV",
        },
    )
    if response.status_code == 200:
        token = response.json().get("refresh_token")
        print("\n" + "=" * 60)
        print(f"✅ REFRESH TOKEN:\n{token}")
        print("You can use your token as your password in your Hyundai integration in Home Assistant.")
        print("=" * 60)
    else:
        print(f"❌ Error: {response.text}")
else:
    print("⚠️ Authorization code not found in URL.")

driver.quit()
input("\nPress Enter to exit...")

```


Secondly, this codes can save as "HyundaiToken.bat" 
```
@echo off
title Hyundai Token Generator
color 0A
cls

echo ============================================================
echo      🚗 Hyundai Token Generator - Cross-Platform
echo ============================================================
echo.
echo Please wait a few seconds. You will be redirected to Hyundai login page by Chrome.
echo.

REM Detect OS
ver | findstr /i "Windows" >nul 2>&1
if %ERRORLEVEL%==0 goto :WINDOWS

REM =====================================
REM Unix/Linux/macOS branch
REM =====================================
:UNIX
#!/bin/bash
echo "============================================================"
echo "      🚗 Hyundai Token Generator - Unix/Mac/Linux"
echo "============================================================"
echo
echo "Please wait a few seconds. You will be redirected to Hyundai login page by Chrome."
echo

# Navigate to script folder
cd "$(dirname "$0")"

# Check python3
if ! command -v python3 &> /dev/null; then
    echo "❌ Python3 not found!"
    exit 1
fi

# Install required packages
python3 -m pip install --user selenium chromedriver-autoinstaller requests > /dev/null 2>&1

# Run Python script
python3 hyundai_token.py

exit 0

REM =====================================
REM Windows branch
REM =====================================
:WINDOWS
REM Navigate to script folder
cd /d "%~dp0"

REM Check Python
where python >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo "❌ Python not found! Please install it from https://www.python.org."
    pause
    exit /b
)

REM Install required packages
python -m pip install --user selenium chromedriver-autoinstaller requests >nul 2>nul

REM Run Python script
python hyundai_token.py

exit /b

```

When you guys have that two files, you can double click HyundaiToken.bat file.

**Comment by stefan-home** [comment]
**Add headless version?**
[script HyundaiTokenTerminal.py is here](https://gist.github.com/stefan-home/808d8774a461f22f2ae1d9519f067b71#file-hyundaitokenterminal-py)
Usage:
- Can use on any terminal without GUI (like SSH on remote computer).
- Run with python. Tested with python3.9. No need for any extra package.
- Start script as `python3 HyundaiTokenTerminal.py`.
- Script is self explaining. It provides some url's to paste into the address-bar of a browser on your main computer and requires you to paste back the response in the script. Script finalises with providing `refresh-token` (to be used as password in the api) and `access-token` (not necessary to use).
- Be sure to set the user-agent of the browser as per instruction of the script. Without correct user-agent the script does not work.

**Comment by knowyourphone** [comment]
hi using the windows code and i keep getting the Chrome/Chromium not found! Install with: sudo apt install chromium-browser error.
i am a total noob when it comes to code so does anyone know what i need to do?

**Comment by sercanincesu** [comment]
> hi using the windows code and i keep getting the Chrome/Chromium not found! Install with: sudo apt install chromium-browser error. i am a total noob when it comes to code so does anyone know what i need to do?

I've upgraded some lines in the codes which I shared previously here. You can download latest version now. Please check here: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/925

**Comment by knowyourphone** [comment]
> > hi using the windows code and i keep getting the Chrome/Chromium not found! Install with: sudo apt install chromium-browser error. i am a total noob when it comes to code so does anyone know what i need to do?
> 
> I've upgraded some lines in the codes which I shared previously here. You can download latest version now. Please check here: [#925](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/925)

ah okay well does seem a bit weird to go to a diffrent website to download a file so no thanks will wait for a fix

**Comment by sercanincesu** [comment]
> > > hi using the windows code and i keep getting the Chrome/Chromium not found! Install with: sudo apt install chromium-browser error. i am a total noob when it comes to code so does anyone know what i need to do?
> > 
> > 
> > I've upgraded some lines in the codes which I shared previously here. You can download latest version now. Please check here: [#925](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/925)
> 
> ah okay well does seem a bit weird to go to a diffrent website to download a file so no thanks will wait for a fix

You are right 👍 ) I couldn't upload .bat file here. That's why I uploaded to google drive. 
I upgraded previous codes a bit in hyundai_token.py, added new lines to fix some issues. If you wanna try, here you go; 
[hyundai_token.py](https://github.com/user-attachments/files/22980690/hyundai_token.py)

**Comment by swepan** [comment]
This code, worked for me, it thows an error, but i work
```
# hyundai_token.py
import os
import re
import time
import shutil
import sys
import requests
import platform
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from selenium.common.exceptions import WebDriverException
from selenium.webdriver.support.ui import WebDriverWait
import chromedriver_autoinstaller

# Detect OS
IS_WINDOWS = platform.system() == "Windows"

# Chrome options
options = Options()
options.add_argument("--window-size=1000,800")
options.add_argument("--disable-blink-features=AutomationControlled")
options.add_argument(
    "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/125.0.0.0 Safari/537.36_CCS_APP_AOS"
)

def install_driver():
    """Ensure a matching chromedriver is installed and return its path."""
    try:
        _ = chromedriver_autoinstaller.get_chrome_version()
    except Exception:
        print("ERROR: Google Chrome not found. Please install Google Chrome and try again.")
        sys.exit(1)

    try:
        driver_path = chromedriver_autoinstaller.install()
        return driver_path
    except Exception:
        return None

def safe_install_and_start():
    """Install chromedriver and start the Chrome WebDriver."""
    driver_path = install_driver()
    if not driver_path:
        try:
            driver_path = chromedriver_autoinstaller.install()
        except Exception as e:
            print(f"ERROR: Failed to install chromedriver: {e}")
            sys.exit(1)

    try:
        service = Service(driver_path)
        driver = webdriver.Chrome(service=service, options=options)
        return driver
    except WebDriverException:
        # Cleanup and retry
        try:
            driver_dir = os.path.dirname(driver_path) if driver_path else None
            if driver_dir and os.path.exists(driver_dir):
                shutil.rmtree(driver_dir, ignore_errors=True)
        except Exception:
            pass

        try:
            driver_path = chromedriver_autoinstaller.install()
            service = Service(driver_path)
            driver = webdriver.Chrome(service=service, options=options)
            return driver
        except Exception as final_err:
            print("ERROR: Could not start Chrome WebDriver after reinstall.")
            print("Reason:", final_err)
            sys.exit(1)

# Start driver
driver = safe_install_and_start()

# Hyundai OAuth base
BASE_URL = "https://idpconnect-eu.hyundai.com/auth/api/v2/user/oauth2/"

# CCSP client details (must be consistent!)
CCSP_CLIENT_ID = "6d477c38-3ca4-4cf3-9557-2a1929a94654"
CCSP_REDIRECT_URI = "https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token"
CLIENT_SECRET = "KUy49XxPzLpLuoK0xhBC77W6VXhmtQR9iQhmIFjjoY4IpxsV"

# Build login URL
LOGIN_URL = (
    f"{BASE_URL}authorize?"
    f"client_id={CCSP_CLIENT_ID}&"
    f"redirect_uri={requests.utils.quote(CCSP_REDIRECT_URI, safe='')}&"
    "response_type=code&"
    "scope=openid+profile+email+phone&"
    "state=ccsp&"
    "ui_locales=en-US&lang=en"
)

driver.get(LOGIN_URL)

print("\n" + "=" * 60)
print("LOGIN REQUIRED:")
print("Please complete login and reCAPTCHA in the opened Chrome window.")
print("=" * 60)
input("\nPress ENTER after login is complete...")

# Wait until redirected URL contains "code="
def url_has_code(driver):
    return "code=" in driver.current_url

try:
    WebDriverWait(driver, 60).until(url_has_code)
except Exception:
    print("Timeout waiting for authorization code in redirect URL.")
    driver.quit()
    sys.exit(1)

redirected_url = driver.current_url
print("Redirected URL:", redirected_url)

match = re.search(r"code=([^&]+)", redirected_url)
if not match:
    print("Authorization code not found in URL. Try logging in again.")
    driver.quit()
    input("\nPress Enter to exit...")
    sys.exit(1)

code = match.group(1)

# Exchange code for token
headers = {
    "Accept": "application/json",
    "Content-Type": "application/x-www-form-urlencoded",
}
data = {
    "grant_type": "authorization_code",
    "code": code,
    "redirect_uri": CCSP_REDIRECT_URI,
    "client_id": CCSP_CLIENT_ID,
    "client_secret": CLIENT_SECRET,
}
response = requests.post(f"{BASE_URL}token", headers=headers, data=data, timeout=30)

print("Token response:", response.text)
if response.ok:
    token = response.json().get("refresh_token")
    if token:
        print("\n" + "=" * 60)
        print(f"REFRESH TOKEN:\n{token}\n")
        print("Use this token as your password in your Hyundai integration in Home Assistant.")
        print("=" * 60)
    else:
        print("No refresh_token in response. Full body above.")
else:
    print(f"Error while retrieving token: {response.status_code} {response.text}")

driver.quit()
input("\nPress Enter to exit...")
```

**Comment by Chris909090** [comment]
Hello together,

I#m sorry but I dont get an token code.
I have an Hyundai and I#m on Windows.

I also try this without any result.

`# hyundai_token_multi_win.py – Hyundai EU (Bluelink), Windows
# Ablauf:
# 1) Script öffnet Chrome (Mobile-UA). Du loggst dich ein (Captcha). Fenster offen lassen.
# 2) Script probiert nacheinander mehrere /authorize-Varianten (mit/ohne PKCE, state/lang/ui_locales).
# 3) Sobald eine URL mit "code=" erscheint, wird der Code gegen den refresh_token getauscht und ausgegeben.

import os, re, time, secrets, hashlib, base64, urllib.parse as up, requests
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# ---- HYUNDAI EU Konstanten ----
CLIENT_ID = "6d477c38-3ca4-4cf3-9557-2a1929a94654"
CLIENT_SECRET = "KUy49XxPzLpLuoK0xhBC77W6VXhmtQR9iQhmIFjjoY4IpxsV"  # Fallback
REDIRECT_URI = "https://prd.eu-ccapi.hyundai.com:8080/api/v1/user/oauth2/token"
AUTH_BASE = "https://idpconnect-eu.hyundai.com/auth/api/v2/user/oauth2/authorize"
TOKEN_URL = "https://idpconnect-eu.hyundai.com/auth/api/v2/user/oauth2/token"

def b64url(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).rstrip(b"=").decode()

def pkce_pair():
    verifier = b64url(secrets.token_bytes(32))
    challenge = b64url(hashlib.sha256(verifier.encode()).digest())
    return verifier, challenge

# ---- Chrome Pfad anpassen falls nötig ----
CHROME_EXE = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
assert os.path.exists(CHROME_EXE), f"Chrome nicht gefunden: {CHROME_EXE}"

# ---- Chrome Optionen ----
opts = webdriver.ChromeOptions()
opts.binary_location = CHROME_EXE
opts.add_experimental_option("detach", True)  # Browser bleibt offen
opts.add_argument("--window-size=1100,850")
opts.add_argument("--window-position=60,60")
# Mobile User-Agent (Hyundai erwartet App-Flow)
opts.add_argument(
    "user-agent=Mozilla/5.0 (Linux; Android 10; SM-G973F) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36"
)

drv = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=opts)

# ---- 1) Login-URL (Captcha), damit du eingeloggt bist ----
login_url = (
    "https://idpconnect-eu.hyundai.com/auth/api/v2/user/oauth2/authorize"
    "?client_id=peuhyundaiidm-ctb"
    "&redirect_uri=https%3A%2F%2Fctbapi.hyundai-europe.com%2Fapi%2Fauth"
    "&nonce=&state=PL_&scope=openid+profile+email+phone"
    "&response_type=code&connector_client_id=peuhyundaiidm-ctb"
    "&connector_scope=&connector_session_key=&country=&captcha=1&ui_locales=en-US"
)
drv.get(login_url)
print("\n[1/3] Im geöffneten Chrome **einloggen** (inkl. reCAPTCHA). Fenster offen lassen.")
input("      Wenn fertig, hier Enter drücken... ")

# ---- 2) Mehrere Varianten des authorize-Calls ausprobieren ----
attempts = [
    # mit PKCE
    {"name": "PKCE + state=ccsp + lang=de",
     "use_pkce": True,  "params": {"state": "ccsp", "lang": "de"}},
    {"name": "PKCE + ui_locales=en-US",
     "use_pkce": True,  "params": {"ui_locales": "en-US", "state": "ccsp"}},
    {"name": "PKCE + ui_locales=de-DE",
     "use_pkce": True,  "params": {"ui_locales": "de-DE", "state": "ccsp"}},
    # ohne PKCE
    {"name": "NO PKCE + state=ccsp + lang=de",
     "use_pkce": False, "params": {"state": "ccsp", "lang": "de"}},
    {"name": "NO PKCE + ui_locales=en-US",
     "use_pkce": False, "params": {"ui_locales": "en-US", "state": "ccsp"}},
]

def build_authorize_url(use_pkce: bool, params: dict, verifier: str = "", challenge: str = "") -> str:
    base = {
        "response_type": "code",
        "client_id": CLIENT_ID,
        "redirect_uri": REDIRECT_URI,  # urlencode später
        "scope": "openid profile email phone",
        # einige Server mögen ein 'nonce' und 'state'
        "nonce": b64url(secrets.token_bytes(16)),
    }
    # feste/optionale Zusätze
    base.update(params or {})
    if use_pkce:
        base["code_challenge"] = challenge
        base["code_challenge_method"] = "S256"
    # saubere QS bauen
    q = []
    for k, v in base.items():
        if k == "redirect_uri":
            q.append(f"{k}={up.quote(v, safe='')}")
        else:
            q.append(f"{k}={up.quote(str(v))}")
    return f"{AUTH_BASE}?{'&'.join(q)}"

found_code = None
used_pkce = False
used_verifier = ""

for i, att in enumerate(attempts, 1):
    print(f"\n[2/3] Versuch {i}/{len(attempts)}: {att['name']}")
    verifier, challenge = pkce_pair()
    url = build_authorize_url(att["use_pkce"], att["params"], verifier, challenge)
    drv.get(url)

    # bis zu 12s auf 'code=' in der URL warten
    try:
        WebDriverWait(drv, 12).until(EC.url_contains("code="))
    except Exception:
        pass

    current = drv.current_url
    print("     Aktuelle URL:", current)
    m = re.search(r"[?&]code=([^&]+)", current)
    if m:
        found_code = m.group(1)
        used_pkce = att["use_pkce"]
        used_verifier = verifier
        print("     ✅ code= gefunden.")
        break
    else:
        print("     ❌ kein code= – nächster Versuch...")

if not found_code:
    print("\n❌ Leider kein 'code=' erhalten. Prüfe:")
    print("- Login wirklich abgeschlossen? (Captcha/Consent)")
    print("- AdBlocker/Script-Blocker deaktivieren (Inkognito probieren)")
    print("- Falls VPN/Proxy aktiv: testweise ohne.")
    raise SystemExit(1)

# ---- 3) Code -> Token tauschen ----
payload = {
    "grant_type": "authorization_code",
    "code": found_code,
    "redirect_uri": REDIRECT_URI,
    "client_id": CLIENT_ID,
}
if used_pkce:
    payload["code_verifier"] = used_verifier

resp = requests.post(TOKEN_URL, data=payload)
if resp.status_code != 200:
    payload["client_secret"] = CLIENT_SECRET
    resp = requests.post(TOKEN_URL, data=payload)

if resp.status_code == 200:
    data = resp.json()
    print("\n" + "="*78)
    print("✅ REFRESH TOKEN (in Home Assistant als PASSWORD eintragen):")
    print(data.get("refresh_token"))
    print("="*78)
else:
    print(f"\n❌ Token-Fehler {resp.status_code}:\n{resp.text}")
`

**Comment by arikatame** [comment]
Can anyone help with the script ?
When I run the original Kia script it opens a Browser window. I use MS Edge that is chromium based but I also installed Chrome only for the script.

<img width="686" height="209" alt="Image" src="https://github.com/user-attachments/assets/7d59ae6c-7267-46eb-838d-79e11cd6e923" />

Any Hyundai script I tried so far fails to find the Chrome install but the Kia script has no issue.
Can someone help me find out what I need to mix together to make it work ?

Hyundai script: iwr -UseBasicParsing -OutFile HyundaiFetchApiTokensSelenium.py https://gist.githubusercontent.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe/raw/

Kia Script:  iwr -UseBasicParsing -OutFile KiaFetchApiTokensSelenium.py https://gist.github.com/fuatakgun/fa4ef1e1d48b8dca2d22133d4d028dc9/raw/fe95ed7c02913f6277878a100458be78b794603d/gistfile1.txt

Any help is appreciated, thanks

**Comment by JanLeshy** [comment]
> I have followed your guide on macOS but the script fails not being able to open chrome although it's there.
> 
> Output:
> 
> ```
> (.venv) ➜  HyundaiToken python3 HyundaiFetchApiTokensSelenium.py
> 
> Chrome/Chromium not found! Install with: sudo apt install chromium-browser
> ```
> 
> EDIT: works with this script: https://gist.githubusercontent.com/Maaxion/22a38ba8fb06937da18482ddf35171ac/raw/442c0b5167d5b092123088055e5a407c034ed720/gistfile1.txt

works for me on Linux, but i must delete and add as new "Hub" in Homeassitant

**Comment by MoOx** [comment]
For macOS, just edit the script function `find_chrome` with

```
def find_chrome():
    paths = ['/usr/bin/chromium-browser', '/usr/bin/google-chrome', 
             '/usr/bin/google-chrome-stable', '/snap/bin/chromium',
             '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome']
```

**Comment by comk22** [comment]
> ### Linux (Ubuntu/Debian)
> # Install dependencies
> sudo apt update
> sudo apt install chromium-browser chromium-chromedriver python3-pip python3-venv
> 
> # Setup and run
> mkdir ~/HyundaiToken && cd ~/HyundaiToken
> python3 -m venv .venv
> source .venv/bin/activate
> pip install selenium requests webdriver-manager
> 
> # Download and run script
> wget -O HyundaiFetchApiTokensSelenium.py https://gist.githubusercontent.com/chrisf4lc0n/d5506bd69e0d07b53574442c972090fe/raw/
> python3 HyundaiFetchApiTokensSelenium.py


`EDIT: Although I got a Token out of this script the login on Home Assistant doesn't seem to be "real". My entities won't be activated. I deleted the the instance in HA and recreated it. I again did a successful token generation and login but no entities were shown. I then entered a wrong PIN just to test if the login works correctly and the login was successful although it shouldnt be. Debug log didn't show anything useful. `

Thanks for the script it worked mostly for Linux Mint Cinnamon. One adaption needs to be made:

- add '/usr/bin/chromium' to the find_chrome path.
```
def find_chrome():
    paths = ['/usr/bin/chromium-browser', '/usr/bin/google-chrome', 
             '/usr/bin/google-chrome-stable', '/snap/bin/chromium', '/usr/bin/chromium']
```
Chromium cannot be installed via apt on Linux Mint (although it is Ubuntu based) but with the Software Manager. It will be saved in said path. Already requested the OP to change the script. Also it is not necessary to install chromium-drivers at least for Linux Mint.

The Hyundai URL is hardcoded to show the polish site. So don't be confused. I tried to change it to DE for Germany but it somehow didn't call the URL correctly then. Not sure why but it is irrelevant since after login you just have to press enter in the terminal and will get the token.

Thanks for the effort! I can't see why this couldn't be added to the official documentation.

**Comment by franckdevaux** [comment]
Is there an issue with the url of the Hyundai connect ?
Because I manage to open it, but when I put my login and password it just says me inaccessible website

**Comment by gurgen16** [comment]
Hello,
I managed to get to the Hyundai Login Page and after entering my Credentials, the Website stated that "ClicktoBuy" would like to access my information. I dared to go 1 step further, when the website turned to some eastern-european language. With this huge red flag, I stopped the process immediately and closed the window. Is this normal, and if so: why does it look so damn fishy?

Edit: I took a step back and looked up what was being displayed: Cl1ck to Buy is an Hyundai service, so no Malware. Why it displayed everything in Polish is still a mistery, but after accepting it all I got the right Token and got my Ioniq5 up and running in HA.
On that note, I also had initial issues with chromium (even though I have it installed on this windows machine). It appears the HyundaiFetchApiTokensSelenium.py for is written only with Linux in mind, so it can't find the right install and even gives Linux-Error Codes on Windows.

I added these paths in the .py and then it worked: 
r'C:\Program Files\Google\Chrome\Application\chrome.exe',
r'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe',

Hope this helps some folks

**Comment by marcelkantor** [comment]
Try this:
[kia_uvo-browser-reauth](https://github.com/marcelkantor/kia_uvo-browser-reauth)

**Comment by cdnninja** [comment]
Here is where I would like to see a single solution go: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/tree/master/KiaHyundaiToken    Feel free to drop PRs to improve this.

**Comment by blka** [comment]
Partially resolved in v4.12.0 via PR #1123 — headless login with username/password is now natively supported for both Kia and Hyundai EU, so the browser-based Selenium guide is no longer needed. A wiki page documenting the new headless login flow (username + password, no token extraction) would still be valuable for users.
